### ISSUE TITLE
Encryption for backup

### ISSUE THREAD

**Issue by RobertBorst** [JackGruber/joplin-plugin-backup#10]
Hi,

Is there a possibility to encrypt the backups?
As I can see now, the content of the .jex files does not seem to be encrypted.
(But this is in line with the .JEX export that also has no encryption of the content.)
As a workaround, I now store the backups on a Veracrypt volume, but it would be nice if the backup used the standard encryption password.

Robert

**Comment by JackGruber** [comment]
I have worked on such a function before, but I don't know if and when it will be available. 

> but it would be nice if the backup used the standard encryption password.

No, it would be a separate password, as the master keys cannot be read by the API.

**Comment by RobertBorst** [comment]
Ok.
Now remains the question: How can I help?

**Comment by JackGruber** [comment]
At the moment, I waiting for a fix in the Joplin Plugin API https://github.com/laurent22/joplin/issues/5072

**Comment by JackGruber** [comment]
Keyed backups are available in [pre-release v1.0.0](https://github.com/JackGruber/joplin-plugin-backup/releases/tag/v1.0.0).
The next normal release will be available as soon as a Joplin stable version newer than `2.1.3` is released, because the new functions need a Joplin version of at least `2.1.3`.
