### ISSUE TITLE
single file for each note

### ISSUE THREAD

**Issue by justsome12** [JackGruber/joplin-plugin-backup#15]
is it possible to have a file for each note? I use the export for easy explorer searching since joplins own search is horrible.

**Comment by JackGruber** [comment]
I will not implement a single JEX export, since this is useless for a restore, unless I would also build a restore function. 
But it's easy to write your own plugin or use the API with powershell, python, shell, ... to create your own export script. 
[Example from the forum](https://discourse.joplinapp.org/t/powershell-script-to-export-notes/13362/5?u=jackgruber)

**Comment by justsome12** [comment]
@JackGruber thank you that works. I have a problem with an error for special characters in the title though e.g. "prediction / correlation" now i can rename them later since windows doesnt allow "/" in names but is it possible to not quit but only give an error and keep trying for the rest of the files?
